global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'flask_app' 
    static_configs:
      - targets: ['<instance1-private-ip>:5000'] 
